name: Deploy SBOM
on:
  push:
    tags:
      - "v*"
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:

      # MARK: CHECKOUT
      - name: Checkout
        uses: actions/checkout@v4

      # MARK: BUILD
      - name: Build
        uses: devcontainers/ci@v0.3
        with:
          push: never
          runCmd: |
            echo "Building SBOM"
            chmod +x ./publish.sh
            echo "GitHub ref: $GITHUB_REF_NAME"
            ./publish.sh "$GITHUB_REF_NAME"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            ./artifacs/sbom-linux-386
            ./artifacts/sbom-linux-amd64
            ./artifacts/sbom-windows-386.exe
            ./artifacts/sbom-windows-amd64.exe
            ./artficats/sbom.json
            
      
        
